services:
  evidence-processor:
    build: .
    container_name: evidence-processor
    environment:
      - EP_CONFIG=/app/defaults/config.yaml
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - /mnt/user/Documents/EvidenceProcessor/data:/data:ro
      - /mnt/user/appdata/evidence-processor/logs:/app/logs
    restart: "no"